default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: shpak

development:
  <<: *default
  database: crypto_messages_development

test:
  <<: *default
  database: crypto_messages_test

production:
  <<: *default
  database: crypto_messages_production
  username: crypto_messages
  password: <%= ENV['CRYPTO_MESSAGES_DATABASE_PASSWORD'] %>
